lab1
Paul-Vasylenko/NodeJS-1 pull request #1
Opened 2022-10-13 07:18 UTC by Paul-Vasylenko

2022-10-13 21:10 UTC, Paul-Vasylenko commented
DEPLOY: https://us-central1-node-js-1-46dfc.cloudfunctions.net/default

2022-10-14 09:02 UTC, nosovk commented on .eslintrc
> +        "ecmaVersion": 2016,
эмм, почему так?

2022-10-14 09:03 UTC, nosovk commented on firebase.json
> +  "functions": [
не хватает блока hosting с rewrite на функцию, к примеру /api:functionname

2022-10-14 09:04 UTC, nosovk commented on functions/tsconfig.json
> +    "module": "commonjs",
хмм, а esm не?

2022-10-14 09:04 UTC, nosovk commented on functions/tsconfig.json
> +    "target": "es2017"
почему таргет для 16 ноды в engines смотрит в далекое прошлое

2022-10-14 09:05 UTC, nosovk commented on functions/ui-debug.log
> +Web / API server started at 127.0.0.1:4000
жто должно быть в игноре

2022-10-14 09:05 UTC, nosovk commented on nodemon.json
> +{
для firebase нужно через emulator, а не через nodemon

2022-10-14 09:05 UTC, nosovk commented on nodemon.json
> +{
оно не работает сейчас поидее

2022-10-17 19:39 UTC, nosovk commented on .editorconfig
> +[{package.json,.travis.yml}]
я думаю travis не предвидится уже

2022-10-17 19:40 UTC, nosovk commented on .editorconfig
> +indent_size = 2
insert_final_newline = true
а в файлике этой линии нет... Выходит IDE не до настроена

2022-10-17 19:41 UTC, nosovk commented on .eslintrc
> +{
json сильно не оптимальный вариант для конфигов, возьми лучше js или yml

2022-10-17 19:41 UTC, nosovk commented on .eslintrc
> +    "extends": ["plugin:@typescript-eslint/recommended", "metarhia", "plugin:sonarjs/recommended", "airbnb-typescript/base"],
конфига prettier не наблюдается, чую могут быть проблемы

2022-10-17 19:41 UTC, nosovk commented on .github/workflows/firebase-hosting-merge.yml
> +      - uses: actions/checkout@v2
уже есть v3

2022-10-17 19:42 UTC, nosovk commented on .github/workflows/firebase-hosting-merge.yml
> +      - run: npm ci && npm run build
а где указание версии node?

и где кеширование?

2022-10-17 19:43 UTC, nosovk commented on .github/workflows/firebase-hosting-merge.yml
> +      - uses: FirebaseExtended/action-hosting-deploy@v0
тут action на хостинг, а где на function?

2022-10-17 19:44 UTC, nosovk commented on firebase.json
> +        "source": "**",
на самом деле это правило можно убрать, и так будет 404.html, но с другим статус кодом.
Это штатаное поведение firebase, см доку.

Но вот ** понадобится для второй лабы, чтобы иметь возможность тестировать роутер на firebase

2022-10-17 19:45 UTC, nosovk commented on functions/src/index.ts
> +admin.initializeApp();
что делает эта штука? Она не понадобится поидее

2022-10-17 19:45 UTC, nosovk commented on functions/tsconfig.json
> +    "target": "es2017"
так остался таргет 2017, как бы не актуально уже для 16й ноды

2022-10-17 19:46 UTC, nosovk commented on package.json
> +    "install": "husky install"
тут явно должен был быть prepare

2022-10-17 19:47 UTC, nosovk commented on public/404.html
> +<!DOCTYPE html>
можешь его удалить и вместо него свой 404 положить

2022-10-17 19:47 UTC, nosovk commented on tsconfig.json
> +{
этот файл не используется похоже теперь

2022-10-18 17:51 UTC, Paul-Vasylenko commented on .editorconfig
> +indent_size = 2
i dont know, think it is solved now :)

2022-10-24 13:30 UTC, nosovk commented on package.json
> +    "build": "npm ci --prefix ./functions/ && npm run build --prefix ./functions/",
build стирает node_modules? Явно не похоже на сборку...

2022-10-24 13:31 UTC, nosovk commented on package.json
> +    "deploy": "npm run deploy --prefix ./functions/",
не будет рабоать без деплоя хостинга

2022-10-24 13:43 UTC, nosovk requested changes
внтури PR не лежат workflows. Одна лаба - один PR, тут часть лабы в мастере, часть в PR

2022-10-26 21:17 UTC, nosovk commented on .firebase/hosting.cHVibGlj.cache
> +404.html,1666119892375,abd7ed7446e79e073af200b7c872e34e3e50f3deb35cda03d14cb0a8165f7f70
.firebase в игнор и удалит из PR

2022-10-26 21:19 UTC, nosovk commented on .github/workflows/actions.yml
> +      uses: w9jds/firebase-action@master
хм, не то что я ожидал если честно. Вы могли просто вызать npm script с аргументом в виде секрета. В живом проекте я бы сказал это удалить, но тут сойдет

2022-10-26 21:20 UTC, nosovk commented on .github/workflows/actions.yml
> +        run: npm ci --prefix functions/
конкретно в вашем случае релизация кеша с условным вызовом `npm ci` даст очень большой выигрыш в скорости, т.к. npm ci каждый раз качает все заново

2022-10-26 21:20 UTC, nosovk commented on .github/workflows/merge.yml
> +			- uses: actions/setup-node@v3
тут что-то сломанно

2022-10-27 07:36 UTC, Paul-Vasylenko commented on .github/workflows/merge.yml
> +			- uses: actions/setup-node@v3
Да, недонастроен эдитор конфиг

2022-10-30 13:56 UTC, nosovk commented
попробуй использовать workspaces  как в примере https://github.com/nosovk/firebase-functions-workspace
тогда npm ci будет ставить зависимости для всех подпапок
И тогда кеширование и деплой будут проще, + это firebase extended action тогда можно выкинуть.

2022-10-30 16:04 UTC, nosovk commented on functions/src/index.ts
> +export const hello = functions.https.onRequest((req: Request, res: Response) => {
я бы кстати оставил версию из примера, с import по требованию. Тогда если у роутов разные наборы зависимостей - они будут инстанициироваться только по требованию.

2022-10-30 16:05 UTC, nosovk commented on functions/package.json
> +    "format:check": "prettier ./**/*.ts --check --ignore-path .gitignore",
для форматера не нужно указывать *.ts
форматер отделен от линтера, как раз именно потому что умеет все виды файлов,  а не только ts\js

2022-10-30 16:06 UTC, nosovk commented on functions/package.json
> +    "firebase-admin": "^10.2.0",
эту зависимость вообще можно удалить

2022-10-30 16:06 UTC, nosovk commented on package.json
> +    "deploy": "firebase deploy",
вместо странного action можно вызвать эту команду

2022-10-30 16:09 UTC, nosovk commented on .github/workflows/actions.yml
> +      uses: w9jds/firebase-action@master
в целом я бы выкинул, и оставил npm run deploy с env переменной, `${{ secrets.FIREBASE_TOKEN }}` уже есть же

2022-10-30 17:05 UTC, nosovk commented
merge

2022-10-30 17:15 UTC, merged